### ISSUE TITLE
Point godaddy domain name to heroku IP addresses

### ISSUE THREAD

**Issue by blobshake** [blobshake/techtasker#3]

**Comment by jasonculbertson** [comment]
What is the ip and I will do this asap

**Comment by blobshake** [comment]
Just sent you the heroku invite, should be able to find it in there and any instructions

**Comment by blobshake** [comment]
Were you able to figure this out?  I sent you a heroku invite, they have pretty good guides on this kind of stuff

**Comment by jasonculbertson** [comment]
I've been working on it.  Not super easy but I had to wait on something for godaddy first so I could change name servers. I was on a flight all day and now at airport. When I get to family's house I'll look into next step.
